wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702747971.53951
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 86
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      - 86
      3:
      - 2
      - 13
      - 23
      4: 3.10.12
      5: 0.16.1
      6: 4.36.1
      8:
      - 1
      - 5
      13: linux-x86_64
